### ISSUE TITLE
Add support for Wicket 7

### ISSUE THREAD

**Issue by martin-g** [thombergs/wicked-charts#59]
Hi,

There is a chance that I will use this library in a Wicket 7 project.
Looking at the code I think the update will be easy.
My question to you is: 
How to make the structure ? 
Do you want a new Maven module for Wicket 7?
I don't expect any API breaks so even the current `wicket6` module should work, but I'll need to update the Wicket dependencies and probably make the optional, so apps could use them with either 6.x or 7.x.
Any preferences?

**Comment by martin-g** [comment]
In addition the upgrade to Highcharts 4.1.10 seems to be as easy as the upgrade of Wicket.

Great work!

**Comment by thombergs** [comment]
It would be best to create a new maven module "wicked-charts-wicket7" and a corresponding wicked-charts-showcase-wicket7" with which one can directly test if everything works (also new chart types coming with highcharts 4 could be added here). If you find any common classes between the wicket6 and wicket7 modules, you might want to move them into a common module.

I do not expect any difficulties for the wicket7 upgrade or the highcharts 4 upgrade (except perhaps the AJAX features...I'm not sure what changed between wicket 6 and 7 on this front). Most of it is simply piece work that just didn't fit into my calendar, since I had no pressure to use it in a project lately :).

If you create a pull request I will take the time to test it and see to it that it be pushed to the maven repos. Looking forward to that! :)

**Comment by martin-g** [comment]
Thanks for your answer!
I'll send the PR in the coming days!
I have it all running locally. I just need to restructure it as you suggested.
